### ISSUE TITLE
データベース接続用のクラスの作成

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#10]
データベースはpostgreSQLを使用
asyncpgを使用

# データベースのユーザークラス

id, MP, HPを保存

# クラスについて

lib/database.py
クラス名: Database

## 関数
`get_user`
ユーザーを返す。ユーザー自体はnamedtupleで作ったUserを使用。なかった場合はNoneを返す

`create_user`
ユーザーを作成する。初期値はHP,MP共に100

`update_user`
ユーザーの値をアップデートする。

**Comment by grarich123** [comment]
DBは作成済みなの？

**Comment by sizumita** [comment]
あ、作成済みではないです
init時にtaskで作成されているか確認するコルーチンを実行して、作成されていなかったら作成するのをお願いできますか？

**Comment by grarich123** [comment]
んー
テーブルは確認できたと思うけどデータベース自体は確認できなかったような気がするけど...
接続時に必要だからなぁ...

**Comment by sizumita** [comment]
あと、データベース名や接続先、ポートは.envファイルに書き込むので、そういう仕組みにお願いします。
ふむ...では作成済みということでお願いします

**Comment by grarich123** [comment]
了解です。

**Comment by grarich123** [comment]
そういえばDBの構造聞いてなかったですね...
その辺のSQL文どうします？

**Comment by sizumita** [comment]
idとHPとMPがあって、idにユーザーid（bigint）、HPとMPが数値ってのでどうでしょう。

**Comment by grarich123** [comment]
なるほど
それで組んでおきます～

**Comment by grarich123** [comment]
テーブル名どうします？

**Comment by sizumita** [comment]
usersでいいかと。ユーザー一覧なので。

**Comment by aiotter** [comment]
This article might help you: https://qiita.com/genzouw/items/35022fa96c120e67c637

**Comment by aiotter** [comment]
I'm not sure this is the right place to discuss the structure of the DB thou

**Comment by grarich123** [comment]
なるほど、ありがとうございます！

**Comment by grarich123** [comment]
.gitnone の中に `lib` が書かれているのでフォルダがコミットできないのですが `lib` のところは消してもいいですか？

**Comment by sizumita** [comment]
あ、大丈夫です。お願いします。（前もなったな...w）

**Comment by grarich123** [comment]
了解です

**Comment by sizumita** [comment]
@grarich123 最後に、Botのclassにdbという名前のインスタンス変数でデータベースを初期化して置いておいてもらえますか

**Comment by grarich123** [comment]
んーと、一回マージした後じゃないとbotのファイルがない()
ので後からでもいいかな？

**Comment by sizumita** [comment]
リベースを覚えてはいかがかな？

**Comment by sizumita** [comment]
https://qiita.com/310ma3/items/e0ec74b47c6c219f2a8b

**Comment by grarich123** [comment]
fmfm
勉強します～

**Comment by grarich123** [comment]
`git rebase maser` で取り込めばいいって理解でOK？

**Comment by sizumita** [comment]
多分そう
僕GitKrakenっていう超素晴らしい最高なGUIアプリでしかやったことないからわからないや...w

**Comment by grarich123** [comment]
えぇ…ｗ

**Comment by grarich123** [comment]
PR出していいかな？

**Comment by sizumita** [comment]
お願いします〜

**Comment by sizumita** [comment]
そこらへんは自己判断で大丈夫ですよ

**Comment by grarich123** [comment]
わかりました
