### ISSUE TITLE
呪文の属性について

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#13]
#8 より

**Comment by Reply127** [comment]
okay

**Comment by Reply127** [comment]
火 : frame
水 : water
木 : nature(仮)
光 : light
闇 : darkness
他4個は決定でok？

**Comment by sevenc-nanashi** [comment]
木が悩みどころ

**Comment by sevenc-nanashi** [comment]
決定でイイと思われ

**Comment by Reply127** [comment]
了解

**Comment by sizumita** [comment]
氷が欲しいです

**Comment by Reply127** [comment]
水と氷か

**Comment by sevenc-nanashi** [comment]
氷は水の派生にするか？

**Comment by yaakiyu** [comment]
派生...そういうのもいいかもですね(ただ派生はアプデでいいかも)

**Comment by Reply127** [comment]
なんなら水なくていいのでは

**Comment by sizumita** [comment]
今のところそんなことどうでもいいので（裏設定いらないと思う）

**Comment by sizumita** [comment]
逆に派生だと何が起こるんですか（）

**Comment by sevenc-nanashi** [comment]
派生と言うより氷＝水でいいんじゃないかな

**Comment by Reply127** [comment]
能力的にはほとんど同じだけど表記はどうしましょう

**Comment by sizumita** [comment]
この際SAOの関係をそのまま使ったらどうでしょうか？

**Comment by sevenc-nanashi** [comment]
いいね

**Comment by yaakiyu** [comment]
SAO好きですかね(僕がTAO好きなので何も言えないけど)

**Comment by Reply127** [comment]
SAOggってくる

**Comment by mov-huyu** [comment]
火と水の合成属性とかにすれば面白いですけど、実装が、、

**Comment by sizumita** [comment]
僕的にら、光と闇、火・水・自然だけでもいいような気がする

**Comment by sizumita** [comment]
（さっき氷って言ったの何っていう）

**Comment by sevenc-nanashi** [comment]
@sizumita  同じく

**Comment by Reply127** [comment]
3?

**Comment by Reply127** [comment]
5か

**Comment by sevenc-nanashi** [comment]
2+3

**Comment by Reply127** [comment]
umm

**Comment by sevenc-nanashi** [comment]
パズドラぱくる？

**Comment by sizumita** [comment]
パクるとかパクらないとか知りませんがそういうゲームはたくさんありますよ

**Comment by mov-huyu** [comment]
最初は火、水、木だけ作って（3）
あとから闇と光を追加(+2）
って認識でいい？

**Comment by sevenc-nanashi** [comment]
イイと思う

**Comment by Reply127** [comment]
木？

**Comment by sevenc-nanashi** [comment]
関係は火＜水＜木（自然？）＜火 かな

**Comment by mov-huyu** [comment]
自然だ

**Comment by Reply127** [comment]
自然っていうよりは一文字に合わせたいところ...(自分の意見)

**Comment by sizumita** [comment]
呪文のところ僕作ろうと思ってましたが、それくらいなら最初から５属性作っても変わらないと思います。

**Comment by sevenc-nanashi** [comment]
> 
> 
> 自然っていうよりは一文字に合わせたいところ...(自分の意見)

それもある

**Comment by Reply127** [comment]
地？

**Comment by mov-huyu** [comment]
F(火)
W(水)
N(自然)
とか、アルファベットにするのはどうだろう

**Comment by Reply127** [comment]
それは意味があるのか..？

**Comment by sevenc-nanashi** [comment]
なんかかっこよさが薄れる…（）

**Comment by sizumita** [comment]
多分楽しくないです

**Comment by mov-huyu** [comment]
了解です

**Comment by sizumita** [comment]
じゃあ、
- 炎`flame`
- 水`water`
- 自然`nature`
- 光`light`
- 闇`umbra`
でいいですかね？

**Comment by sevenc-nanashi** [comment]
- 炎`flame`
- 水`water`
- 地`nature`
- 光`light`
- 闇`umbra`

**Comment by sizumita** [comment]
natureって単語に地っていう意味ない気がしますが...

**Comment by sevenc-nanashi** [comment]
どうしよう…

**Comment by Reply127** [comment]
groundはなんかダサいな

**Comment by sevenc-nanashi** [comment]
earth?（壮大すぎかな）

**Comment by Reply127** [comment]
かっこいい名前を求めてるので壮大がちょうどいいと思います

**Comment by sizumita** [comment]
それ絶対に勝てそうだからダメw

**Comment by sevenc-nanashi** [comment]
- 炎`flame`
- 水`water`
- 地`earth`
- 光`light`
- 闇`umbra`
カッコイイ

**Comment by Reply127** [comment]
かっこいい！きれい！

**Comment by sizumita** [comment]
じゃあそれで行くってことでcloseしていいですかね

**Comment by sevenc-nanashi** [comment]
文字数が同じなのもまたよき

**Comment by sevenc-nanashi** [comment]
これでいいね

**Comment by Reply127** [comment]
> じゃあそれで行くってことでcloseしていいですかね
私はこれでいいと思います

**Comment by sizumita** [comment]
closeします（間違って他のとこcloseしたなんていえんw）
