### ISSUE TITLE
呪文の武器の形状について

### ISSUE THREAD

**Issue by sevenc-nanashi** [sizumita/aria#14]
```
change element to <形状>
```
のやつ

分けた方が良いかなと

**Comment by sevenc-nanashi** [comment]
タイトル変更サンクス

**Comment by Reply127** [comment]
なるほど。槍と剣...ほとんど同じだな...
かっこよさで考えると剣かな？異論は認める

**Comment by sizumita** [comment]
武器にも耐久と攻撃力があって、例えば耐久よりも攻撃力が高いとそっちが勝って攻撃が入るとかを考えています。
武器同士で消滅させ合いとかもありだと思うので

**Comment by sevenc-nanashi** [comment]
消滅いいね

**Comment by Reply127** [comment]
その発想はなかった

**Comment by Reply127** [comment]
なんかメモ帳のissueを...

**Comment by sevenc-nanashi** [comment]
炎剣：消費MP大、高威力
氷剣：消費MP小、低威力
みたいなのあったらおもしろそう

**Comment by sizumita** [comment]
https://github.com/sizumita/aria/wiki/呪文について

**Comment by sizumita** [comment]
小さい武器ほどMP消費が少ないのは自明
そこら辺まとめて後で出すので武器の種類を考えるのお願いします

**Comment by Reply127** [comment]
了解です

**Comment by sevenc-nanashi** [comment]
- 剣・槍（？）
- 弓
- 杖

**Comment by sevenc-nanashi** [comment]
とりあえず思いついた奴

**Comment by Reply127** [comment]
剣と槍...

**Comment by sizumita** [comment]
長剣短剣片手剣両手剣色々ありますが

**Comment by sizumita** [comment]
槍は早く飛ぶとかすれば良さそうですわね

**Comment by sevenc-nanashi** [comment]
マイクラのデータ値みたいにsword:0（長剣）、sword:1（短剣）とかよさそう

**Comment by sizumita** [comment]
そこまでする必要はないと思います

**Comment by Reply127** [comment]
開発が...

**Comment by Reply127** [comment]
10種類あれば十分なんかな？

**Comment by mov-huyu** [comment]
武器じゃないけど盾を入れたら戦略性上がりそう

**Comment by sevenc-nanashi** [comment]
武器じゃないけどwallとか？

**Comment by Reply127** [comment]
槍と剣についてはどちらも武器でok？
槍 : 速度`速`, 攻撃`弱`
剣 : 速度`普通`, 攻撃`強`

**Comment by Reply127** [comment]
壁生成、いいね

**Comment by Reply127** [comment]
意見案メモ
・剣
・槍
・弓
・壁
・杖

**Comment by Reply127** [comment]
銃は反則ですか？

**Comment by sevenc-nanashi** [comment]
微妙…
どうやってバランスを取るのかという

**Comment by Reply127** [comment]
速い、強い
みんな選ぶねｗ

**Comment by sevenc-nanashi** [comment]
あと弓との差別化が

**Comment by yaakiyu** [comment]
まぁとりあえず作ってみないと細かいバランスはわかりませんから、現状で一回開発すべきかと

**Comment by Reply127** [comment]
あー

**Comment by mov-huyu** [comment]
5種でいいと思うんだけど
もっとあった方がいい？

**Comment by disneyresidents** [comment]
>>> 意見案メモ
・剣
・槍
・弓
・壁
・杖
とりあえずはこの感じで良さげ

**Comment by Reply127** [comment]
>5種でいいと思うんだけど
もっとあった方がいい？ 

開発は長くなるけど多い方が面白いよね。

**Comment by sizumita** [comment]
とりあえずその五種類で、まずバランスを取れるようにした方がいいかと思います。

**Comment by Reply127** [comment]
杖について詳しく知りたい @sevenc-nanashi

**Comment by mov-huyu** [comment]
MP消費大だと予想

**Comment by sevenc-nanashi** [comment]
武器といえばってやつで出したから詳しく考えてない（）

**Comment by Reply127** [comment]
・剣 : 速度`普通`, 強さ`普通`
・槍 : 速度`速`, 強さ`弱`
・弓 : 速度`速`, 強さ`普通`
・壁 : None
・杖 : ?

んーバランス難しいね。huyuさんの通りMPも調整しないと...

**Comment by sevenc-nanashi** [comment]
杖：速度`遅`, 強さ`強`？

**Comment by sizumita** [comment]
> 意見案メモ
> ・剣
> ・槍
> ・弓
> ・壁
> ・杖

形状はこれでいいと思うので、効果とかの話は他のissueでお願いします

**Comment by sizumita** [comment]
あと他のissueは後で立てるので、discordで話してもらえると嬉しいです
