### ISSUE TITLE
requirements.txtの整備

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#2]

**Comment by sevenc-nanashi** [comment]
--コピペ--
はじめに

PythonのDjangoを使っていると、githubに共有したり、本番環境に反映させるときになどに、ローカルで作業したものをインストールしたソフトなどを反映させる必要があります。

そんなときに便利なのが「requirements.txt」です。

一言でいうと、対象のプロジェクトにpip installする必要があるパッケージリストを記載しているファイルです。

「requirements.txt」を使うことで環境構築の手間を削減することができるのです。
