### ISSUE TITLE
ユーザーの現在の最大HP,MPを確認できるコマンド

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#24]
cogs/manage.pyに作成する
コマンド名は`status`コマンド。
フォーマット:

```
{メンション} さんのステータス
HP: {}HP
MP: {}MP
```

**Comment by sevenc-nanashi** [comment]
HPって単位なのかな…？

**Comment by yaakiyu** [comment]
最大HP,MPだけじゃなくて今のHP、MPも表示させるべきだと思います。

**Comment by sizumita** [comment]
それは他のコマンドで実装すべきだと思います。ゲーム中に自動表示させる可能性もあるので。
