### ISSUE TITLE
Dockerfileの整備

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#3]
BotをDockerで動かすため

**Comment by yaakiyu** [comment]
**Dockerfileとは**
Dockerfile により、ベースとなるイメージを元に必要なパッケージやファイルをインストールし、新たなイメージを作成する作業を自動化することができます。下記の例では、centos:7 イメージをベースとして、Apache (httpd) をインストールし、新たなイメージを作成します。

自分がわからなかったのでとりあえずメモ

**Comment by sevenc-nanashi** [comment]
必要なapiとかを書いておくファイルって認識でおｋ？

**Comment by yaakiyu** [comment]
Docker（ドッカー）は、コンテナ仮想化を用いてアプリケーションを開発・配置・実行するためのオープンソースソフトウェアあるいはオープンプラットフォームである。 

👆DockerがわからないとfileついてもわからなさそうだったのでDockerについてもメモ(wikipediaより)

**Comment by yaakiyu** [comment]
![image](https://user-images.githubusercontent.com/62779277/89705389-ed22ee80-d997-11ea-8f04-b5e3247ad3f1.png)

**Comment by yaakiyu** [comment]
↑ネットで拾った画像です

**Comment by yaakiyu** [comment]
で、ここどうでしょう?(closeされていないところの定期チェック)
