### ISSUE TITLE
対戦申し込みコマンドの作成

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#37]
対戦申し込みコマンドの作成
`apply @メンション`で、対戦相手に対戦を申し込める
相手はリアクションでやるかやらないか決められる（同じチャンネルで）
そのあとゲームを始める関数を実行する（作っていない）

**Comment by daima3629** [comment]
メモ
- メンション指定先が登録されているユーザーか確認
- wait_forでリアクション待つ, 60秒ぐらい
- cooldownつける(30sぐらい)

**Comment by daima3629** [comment]
ゲームスタート関数
![image](https://user-images.githubusercontent.com/52790780/89733210-e1662380-da8e-11ea-90fb-984da7b43510.png)

**Comment by sizumita** [comment]
ゲームスタート関数変わったのでお知らせしておきます

```python
from lib.game import DiscordGame
game = DiscordGame(bot, user1, user2, ctx.channel, cox.send)
await game.start()
```

**Comment by sizumita** [comment]
後今からマージするので、リベースして動作確認お願いします

**Comment by daima3629** [comment]
> ゲームスタート関数変わったのでお知らせしておきます
> 
> ```python
> from lib.game import DiscordGame
> game = DiscordGame(bot, user1, user2, ctx.channel, cox.send)
> await game.start()
> ```

`cox.send`とはなんでしょう...

**Comment by sizumita** [comment]
ctx.sendだ、すまん

**Comment by sizumita** [comment]
と言うかマージしたのでリベースお願いしますね

**Comment by daima3629** [comment]
あ、了解ですー

**Comment by daima3629** [comment]
`git rebase master`でいいんですよね...?

**Comment by sizumita** [comment]
頑張れ！多分大丈夫！

**Comment by sizumita** [comment]
一旦githubにそこまでをpushしておけば、一回全部消せばcloneして元に戻せるからやっといたほうがいいかもよ

**Comment by daima3629** [comment]
もうやっちゃった()

**Comment by daima3629** [comment]
無事成功

**Comment by sizumita** [comment]
よかった！
