### ISSUE TITLE
discord.py のインストールで自動的に入るものについての記述って必要かな？

### ISSUE THREAD

**Issue by chun37** [sizumita/aria#40]
これ修正されてない気がする…

> discord.py のインストールで自動的に入るものについての記述って必要かな？

_Originally posted by @chun37 in https://github.com/sizumita/aria/pull/4#issuecomment-670845557_

**Comment by sizumita** [comment]
申し訳ない、まだ修正できてないです。やっておきます。

**Comment by sizumita** [comment]
変更いたしましたのでマージします。
