### ISSUE TITLE
ゲームのランキング機能

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#48]
ゲームではHPとMPが増えたり減ったりするので、それを元にランキングを作りたい
具体的には、HPとMPの合計でランキングを作る。トップ10と自分のランキングを乗せる。

```py
1:
2:
3:
4:
5:
6:
7:
8:
9:
10:
自分:
```

cogs/manage.pyにrankingコマンドとして実装し、lib/databaseのDatabaseクラスにランキングを取得するコルーチンを作る。
ランキングのソートはできればSQLの方でやりたい。

**Comment by Raclett3** [comment]
select (hp + mp) as strength, プレイヤーの識別子的なやつ from なんとか order by strength desc
的なやつ
