### ISSUE TITLE
ゲームに勝った・負けた時の処理

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#54]
MP/HPを増やす・減らす
倍率はどれくらいがいいですかね？

**Comment by sizumita** [comment]
相手と自分の差を考慮して、1割ぐらいで考えたいと思います。

**Comment by Reply127** [comment]
勝った時の倍率で1割はちょっと少ないと思った

**Comment by sizumita** [comment]
勝った時は２割ぐらいでいいですかね
でも多すぎると一気に差が開きすぎるので、あんまり上がらない方がいいんですよね
それなら負けたら0.5割、勝ったら1割とかですかね。

**Comment by Reply127** [comment]
いいと思います

**Comment by Reply127** [comment]
別の案になるけど、DBDみたいに試合中で稼いだポイント(？)でMP/HPを増やすっていうのも面白いと思った。
コードが面倒になりそうだけど...

**Comment by sizumita** [comment]
多分最初は簡単な方がわかりやすいかなと思います
