### ISSUE TITLE
ゲーム進行について

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#7]
ゲーム進行について
基本的に1v1を考えています。

- 双方の了承を得る
- ゲームがスタートする
- ゲームが終了する
- リザルト表示
- 双方のパラメーターの変更

**Comment by yaakiyu** [comment]
ゲーム進行はこれで問題はないと思います

**Comment by yaakiyu** [comment]
で、ここどうでしょう?(closeされていないところの定期チェック)
