### ISSUE TITLE
降参コマンドが欲しい

### ISSUE THREAD

**Issue by sevenc-nanashi** [sizumita/aria#72]
「急に呼び出された」 「負け確」
みたいなときのために降参コマンドが欲しいんですけれど、皆さんはどうなんでしょう

**Comment by sizumita** [comment]
まず急に呼び出されることはありません。また、負け確の時に降参されると何ももらえないことになり、大変つまらないと思います。

**Comment by sevenc-nanashi** [comment]
ギリギリで降参→±０みたいになっちゃうのか…
要らないなぁ
