### ISSUE TITLE
Botのprefixを.envファイルで設定すると、末尾の空白が認識されない

### ISSUE THREAD

**Issue by chun37** [sizumita/aria#79]
デフォルトでは、`aria ` がprefix となっているが、
```
BOT_TOKEN=hoge
PREFIX=fuga 

```
と書いたときに、`fuga ` ではなく `fuga` が prefix になってしまう。
.env ファイルを読んだ時に、末尾の空白を trim してしまうらしい。

**Comment by sizumita** [comment]
`PREFIX="fuga "`でいけませんかね？

**Comment by chun37** [comment]
行けました。
クオートすれば良いことを完全に忘れてました。
