### ISSUE TITLE
ユーザーについて

### ISSUE THREAD

**Issue by sizumita** [sizumita/aria#9]
ユーザーはHPとMPを持っており、HPを削り切られるとバトルに負ける。
バトルに勝つとHPかMPが増える。負けると相手が増えた分減る。

**Comment by sevenc-nanashi** [comment]
減らすとひたすら沼りそうだからやめた方が良いと思う

**Comment by yaakiyu** [comment]
うーん...そうなると、HP総量が参加人数×元のHPのまま推移しますよね。
となると、、ゲームに面白みは出てくるのでしょうか....
一度負けるとそのまま負け続けやめてしまう人が出ると思います。

**Comment by sizumita** [comment]
減らないとひたすらサブ垢で負けさせて増やす人が出ますね

**Comment by sevenc-nanashi** [comment]
デフォ値以下には減らないようにするとか…？

**Comment by sizumita** [comment]
例えば自分よりある程度HPなどが低いユーザーと戦っても、高いユーザーが勝っても低いユーザーは減らず、高いユーザーは増えない（逆は減ったり増えたりする）のはどうでしょうか。

**Comment by Raclett3** [comment]
雑魚を狩っても成長はしないけど、強い人に勝てると成長がたくさん得られる
同じ人と戦っても新たなアイデアは得られないが、いろいろな人と戦うとアイデアを得られて成長に繋がる
的なやつ

**Comment by yaakiyu** [comment]
あー、そういう見本がズーキーパーにありました。

**Comment by yaakiyu** [comment]
レート制度ですね

**Comment by sizumita** [comment]
そんな感じです！

**Comment by grarich123** [comment]
fmfm
1週間に一回くらいリセットできるような選択があっても面白そう

**Comment by sevenc-nanashi** [comment]
> 
> 
> 雑魚を狩っても成長はしないけど、強い人に勝てると成長がたくさん得られる
> 同じ人と戦っても新たなアイデアは得られないが、いろいろな人と戦うとアイデアを得られて成長に繋がる
> 的なやつ

いいねそれ

**Comment by yaakiyu** [comment]
で、ここどうでしょう?(closeされていないところの定期チェック)

**Comment by shimonny** [comment]
> fmfm
> 1週間に一回くらいリセットできるような選択があっても面白そう

シーズン制みたいな？

**Comment by shimonny** [comment]
シーズン制とかあったほうがいいのかな?

**Comment by mov-huyu** [comment]
それは後回しだと思う
今はスプラで言うナワバリバトルを作った方がいい
フェスは後

**Comment by shimonny** [comment]
> それは後回しだと思う
> 今はスプラで言うナワバリバトルを作った方がいい
> フェスは後

スプラわからんが言いたいことはわかりましたー

**Comment by mov-huyu** [comment]
ごめんイベントとかと勘違いしてた
シーズンって一定期間でレベルとかレートをリセットするってこと？(フォトナとかクラロワみたいな)

**Comment by shimonny** [comment]
そんなかんじですねー、もともとのレートをもとに次のシーズンのレートを決めるみたいな(リセットでもいいけどもね)

**Comment by sizumita** [comment]
面白そう
でもそれはテストが終わってからだね
まだbotすらないので皮算用に...

**Comment by sevenc-nanashi** [comment]
とりあえず基本部分だけでも動かすのが重要だと思われ

**Comment by shimonny** [comment]
そうね、考えるの楽しいな
